WIP: adding plugins as modules
lordkekz/nix-yazi-plugins pull request #9
Opened 2024-12-16 15:10 UTC by haennes

So this is just an idea i had lying around for quite some time.
# Motivation
Just add plugins as easy as with nixvim:
```nix
  programs.yazi.yaziPlugins = {
    enable = true;
    plugins = {
      bypass.enable = true;
      bypass.package = pkgs.custom-bypass;
      chmod.enable = true;
      chmod.package = null; # do not add chmod to programs.yazi.plugins
      full-border.enable = true;
      hide-preview.enable = true;
      starship.enable = true;
       jump-to-char = {
        enable = true;
        keys.toggle.on = [ "F" ];
      };
      max-preview.enable = true;
      smart-filter.enable = true;
      relative-motions.enable = true;
    };
  };

```
# General Notes:
- i renamed default.nix -> package.nix
  - it still gets converted to a package using callPackage. (files can just be renamed)
  - `$ rename default.nix package.nix */*`
# exmple config (bypass.nix): 
```nix 
{
  options = { cfg, mkKeyOption, ... }:
    { lib, ... }: {
      keys = { # actually programs.yazi.yaziPlugins.bypass.keys =
        left = mkKeyOption {
          on = [ "l" ];
          run = "plugin bypass --args=smart_enter";
          desc =
            "Open a file, or recursively enter child directory, skipping children with only a single subdirectory";
        };
        right = mkKeyOption {
          on = [ "h" ];
          run = "plugin bypass --args=reverse";
          desc =
            "Recursively enter parent directory, skipping parents with only a single subdirectory";
        };
      };
    };
  config = { cfg, setKeys, ... }:
    { config, lib, ... }: # no need to check if enabled as it is already done for us
    { } // (setKeys cfg.keys);
}
```
# Quality of life improvements:
  -  The first argument (attrset) of both the config and option function:
     - cfg = config.programs.yazi.yaziPlugins.PLUGINNAME
     - all other following attrs are the ones defined in ./lib.nix
   - the options **enable**, and **package** are **automatically declared** for each plugin and given sensible defaults
   - a plugin can have runtimeDependencies (fg needs some for example)
   - config is only called if it is enabled
   - all options are automatically mapped to a child of config.programs.yazi.yaziPlugins.PLUGINNAME
   - lib:
     - setKeys: easily add keys (given as second argument) to ` programs.yazi.keymap.manager.prepend_keymap`
     - mkKeyOption: generates simple nested options for keys (see above)

# Some Notes regarding the things to fix:
- the remaining x86_64-linux reference for packages:
  - could be moved into the output builder in expense for having to use homeManagerModules.x86_64-linux to import
  - fix it in any other way (using the pkgs.system from the import yields a infinite recursion error (at least in the way i did it))
- more cleanly seperate which lib is being used
- flake.nix is quite crammed and unorganized. (open for suggestions on renaiming and introducing new intermediary variables)

2024-12-16 17:26 UTC, Mcrtin commented
how about an option for adding/not adding required packages for the plugin

2024-12-16 17:34 UTC, haennes commented
> how about an option for adding/not adding required packages for the plugin

This is a good idea! I would leave it enabled by default, but giving the option to opt of this is actually quite important
For each one individually, for all at once or for all at one with the individual one overwriting it?

2024-12-16 17:45 UTC, Mcrtin commented
for each one individually should be fine; disabling that behavior should only be an edge case; most plugins don't work without their packages after all

2024-12-16 18:01 UTC, haennes commented
> for each one individually should be fine; disabling that behavior should only be an edge case; most plugins don't work without their packages after all

ok, easiser done than said :joy: just setting the package to null removes it

2025-01-12 13:15 UTC, Mcrtin commented
how is this going?

2025-01-15 21:29 UTC, haennes commented
Finally got around to take a look at it again.
I am still getting some infinite recursion errors, when trying to get rid of the hardcoded x86_64-linux.
I have published both of my tries which yield such errors:
- [first](https://github.com/haennes/nix-yazi-plugins/commit/974c06e0e6c789bb36852cf9a4a0b9f89a8ed67f)
- [second](https://github.com/haennes/nix-yazi-plugins/commit/b133cef6dcb34f0d44d322c6219628387528dcc5)

Does  anyone else have a way of solving this, without having to expose the hm module as a function base on platform, or having to expose multiple hm modules, one for each platform?

2025-01-16 08:15 UTC, Mcrtin commented
`inputs.nvim.packages.${pkgs.stdenv.hostPlatform.system}.full`
idk if this works of this use case but that's how i did it with my nixvim config

2025-01-16 20:06 UTC, haennes commented
> `inputs.nvim.packages.${pkgs.stdenv.hostPlatform.system}.full` idk if this works of this use case but that's how i did it with my nixvim config

see updated comment

2025-01-17 14:51 UTC, Mcrtin commented
https://github.com/nix-community/home-manager/issues/3075#issuecomment-1330661815
here this was resolved by moving the homemanager attribute set into packages

2025-01-18 09:32 UTC, haennes commented
This would basically result in something like this: `homeManagerModules.x86_64-linux` or `homeManagerModules.yaziPlugins.x86_64-linux`
I prefer not to move the module into pkgs, as it isn´t really a package (as mentioned on the issue).
@lordkekz are you ok with that? 
I think i would be ready for review, if this would be resolved.

2025-01-18 13:02 UTC, lordkekz commented
From a quick glance, it looks nice. I'll properly test and review it soon™ (probably this evening or tomorrow).
Thanks for your work btw!

> This would basically result in something like this: `homeManagerModules.x86_64-linux` or `homeManagerModules.yaziPlugins.x86_64-linux` I prefer not to move the module into pkgs, as it isn´t really a package (as mentioned on the issue). Moving this into a pkg, might lead beginners to conclude that they just have to add it to their environment packages @lordkekz are you ok with that? I think i would be ready for review, if this would be resolved.

I would prefer to use `legacyPackages.${system}.homeManagerModules.whatever` because other projects use it similarly, as  @Mcrtin said in https://github.com/lordkekz/nix-yazi-plugins/pull/9#issuecomment-2598535898.

My dream solution would be more like nixvim's standalone mode where we use modules to build a wrapper which provides the closure of yazi, the plugins, the plugin dependencies and the configuration. The resulting package could then simply be added to `home.packages` or `environment.systemPackages` or wherever you want really. This has several benefits:
- It would be possible to run yazi with unstable nixpkgs but the desktop with stable nixpkgs, as I personally do with nixvim already. This saves me a lot of build failures.
- It would also prevent theuglinesss of requiring system-specific home modules.
- It would make it easier to analyze your system closure size with tools like [nix-tree](https://github.com/utdemir/nix-tree). With this PR, they can't see that e.g. a big plugin dependency is caused by yazi since there is no dependency between the derivations currently.
- It doesn't require home-manager activation or symlinking stuff in `~/.config/yazi` to work.

But I think that using home-manager modules is a huge step in the right direction and almost all of the plugin-specific work will carry over to a standalone mode, so I'd be happy to merge this PR soon™ (after testing) and look into the standalone mode when I have more free time in late february or march (unless you have time and interest in doing it before then).

2025-01-20 00:40 UTC, lordkekz requested changes
It's looking good! :rocket:
I left some hopefully non-troublesome suggestions, and once those are addressed, I'm happy to merge this :)

2025-01-20 00:40 UTC, lordkekz commented on plugins/copy-file-contents/default.nix
> +    description = "Add a full border to Yazi to make it look fancier.";
Please update this description.

2025-01-20 00:40 UTC, lordkekz commented on plugins/relative-motions/hm-module.nix
> +        ) (lib.range 1 9)
You can write this slightly shorter using `lib.genList`, see [my current config](https://github.com/lordkekz/dotfiles/blob/8d1afd1aa383518a6e5cc9346fc95f50c9dc8546/homeProfiles/terminal/yazi.nix#L62).
```suggestion
        lib.genList (
          idx_n:
          let
            idx = builtins.toString idx_n;
          in
          {
            name = idx;
            value = mkKeyOption {
              on = [ idx ];
              run = "plugin relative-motions --args=${idx}";
              desc = "Move in relative steps";
            };
          }
        ) 9
```

2025-01-20 00:40 UTC, lordkekz commented on plugins/relative-motions/hm-module.nix
> +        require("starship"):setup()
You forgot to change the plugin name here.

Also, there's some options for relative-motions which can be configured by passing a map to the setup function, see [my current config](https://github.com/lordkekz/dotfiles/blob/8d1afd1aa383518a6e5cc9346fc95f50c9dc8546/homeProfiles/terminal/yazi.nix#L118). The options are documented in a table in the [relative-motions README](https://github.com/dedukun/relative-motions.yazi?tab=readme-ov-file#configuration).
Could you please make these options configurable via this module?

If you don't want to define each option explicitly I'd be happy with a freeform `settings` option that you pass through e.g. [`lib.generators.toLua`](https://noogle.dev/f/lib/generators/toLua).

2025-01-20 00:40 UTC, lordkekz commented on flake.nix
> +
This will use the `lib` from our flake's input, but maybe it'd be better to use the `lib` from whatever nixpkgs the overlay is applied to? I think the following would work, but haven't tried to eval it in context so there might be infinite recursion due to `final`:
```suggestion
      overlays.default = final: prev: { yaziPlugins = (instantiate_lib (final.lib) prev).packages; };

```

2025-01-20 00:40 UTC, lordkekz commented on lib.nix
> +        to deactivate overlaying lib.mkForce [] the parent option
```suggestion
        to deactivate overlaying `lib.mkForce []` the parent option
```

2025-01-20 00:40 UTC, lordkekz commented on module.nix
> +        lib.mkForce []
```suggestion
        Additional runtime packages to make available for yazi and plugins.
        To deactivate overlaying set this to `lib.mkForce []`.

        This gets set by some plugin modules.
```

2025-01-20 00:40 UTC, lordkekz commented on flake.nix
> +            };
Sorry to bring this up again, but I meant for you to put this into `legacyPackages`, not `packages`, as this breaks `nix flake show` (whereas `legacyPackages` is expected to contain unexpected and nested things).

2025-01-20 09:23 UTC, haennes commented on flake.nix
> +            };
Sorry.
Additionally the static use of x86_64-linux was a copy paste error.  fixed in in the "fix use {system}" commit

2025-01-20 09:35 UTC, haennes commented on plugins/copy-file-contents/default.nix
> +    description = "Add a full border to Yazi to make it look fancier.";
should this be an extra pr, as i just renamed this file :thinking:

2025-01-20 09:44 UTC, haennes commented on plugins/relative-motions/hm-module.nix
> +        ) (lib.range 1 9)
[fixed](https://github.com/lordkekz/nix-yazi-plugins/pull/9/commits/d569553e09bcb94ba72d1be43300a1c3b17dfe13)

2025-01-20 14:52 UTC, haennes commented on plugins/relative-motions/hm-module.nix
> +        require("starship"):setup()
[done and tested](https://github.com/lordkekz/nix-yazi-plugins/pull/9/commits/a77b917779b306ed3af40736aef67d5fb10273de)

2025-01-20 15:25 UTC, haennes commented
Ok, I think im done, did everything as requested, except for updating the description of copy-file-contents.
Another thing that came to mind, that we might want to fix in **a different** PR: As we have some plugins that will bind the same keys to different actions by default, a **random** one will take precedence, "shadowing" the other plugin.
I will make a separate issue for this, I think, in which we can discuss, if we want to fix this.

2025-01-20 16:25 UTC, lordkekz approved these changes
Nice! I simplified the lua conversion in relative-motions a bit; it now behaves slightly differently in that it explicitly serializes the enum to `nil` in Lua if the option was set as `null` in Nix. That doesn't seem to be an issue though, it works as expected with relative-motions.

Excerpt from an init.lua as generated _after_ my change:
```lua
require("relative-motions"):setup({
  ["only_motions"] = false,
  ["show_motion"] = true,
  ["show_numbers"] = nil
})
```

I'll merge it now, thanks!

2025-01-20 16:26 UTC, haennes commented on plugins/copy-file-contents/default.nix
> +    description = "Add a full border to Yazi to make it look fancier.";
As mentioned below i didn´t fix this, but i already have a commit lying around, that fixes this and another description and updates the readme. See #13

2025-01-20 16:27 UTC, haennes commented
Nice, dont have any experience with lua, so i didnt want to touch anything in that regard :)

2025-01-20 16:30 UTC, merged